version: '3'
services:
    mysql:
        image: mysql:8.0.31
        ports:
            - 3306:3306
        command:
            - "mysqld"
            - "--default-authentication-plugin=mysql_native_password"
            - "--innodb_buffer_pool_size=400M"
            - "--ft-min_word-len=1"
            - "--innodb_ft_min_token_size=1"
            - "--ft-stopword-file=''"
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "dormiday"
            MYSQL_PASSWORD: "password"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1 
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - server
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-ppassword"]
            retries: 3
            timeout: 5s
    nginx:
        image: nginx
        ports:
            - 8888:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/
        networks:
            - server
        depends_on:
            - mysql
            - backend
            - frontend
    backend:
        image: node:latest

        working_dir: /var/www

        command: bash -c "
            npm install &&
            npm run migrate &&
            npm run dev"

        restart: always

        networks:
            - server
        volumes:
            - ./backend:/var/www/
        depends_on:
            - mysql
    frontend:
        image: node:latest

        working_dir: /var/www

        entrypoint: /bin/sh -c "sh entrypoint.sh; sleep infinity"

        restart: always

        ports:
            - 11111:11111 # hmr
        volumes:
            - ./frontend:/var/www/
        networks:
            - server
networks:
    server:
        driver: bridge
volumes:
    mysql:
        driver: local